In [1]:
import pandas as pd

stores_raw = pd.DataFrame([
    {"store_id": "FL-239", "store_name": "Walmart Supercenter Orlando", "city": "Orlando", "state": "FL", "zip_code": "32801", "latitude": 28.5383, "longitude": -81.3792, "region": "Central"},
    {"store_id": "FL-105", "store_name": "Walmart Supercenter Tampa", "city": "Tampa", "state": "FL", "zip_code": "33602", "latitude": 27.9506, "longitude": -82.4572, "region": "West"},
    {"store_id": "FL-330", "store_name": "Walmart Supercenter Miami", "city": "Miami", "state": "FL", "zip_code": "33101", "latitude": 25.7617, "longitude": -80.1918, "region": "South"},
    {"store_id": "FL-412", "store_name": "Walmart Supercenter Jacksonville", "city": "Jacksonville", "state": "FL", "zip_code": "32099", "latitude": 30.3322, "longitude": -81.6557, "region": "North"},
    {"store_id": "FL-287", "store_name": "Walmart Neighborhood Market Kissimmee", "city": "Kissimmee", "state": "Florida", "zip_code": "34741", "latitude": 28.292, "longitude": -81.4076, "region": "Central"},
    {"store_id": "FL-156", "store_name": "Walmart Supercenter Daytona Beach", "city": "Daytona Beach", "state": "FL", "zip_code": "32114", "latitude": 29.2108, "longitude": -81.0228, "region": "East"},
    {"store_id": "FL-501", "store_name": "Walmart Supercenter Fort Myers", "city": "Fort Myers", "state": "FL", "zip_code": "33901", "latitude": 26.6406, "longitude": -81.8723, "region": "West"},
    {"store_id": "FL-078", "store_name": "Walmart Supercenter Gainesville", "city": "Gainesville", "state": "FL", "zip_code": "32601", "latitude": 29.6516, "longitude": -82.3248, "region": "North"},
    {"store_id": "FL-619", "store_name": "Walmart Supercenter Tallahassee", "city": "Tallahassee", "state": "FL", "zip_code": "32301", "latitude": None, "longitude": None, "region": " Panhandle"},
    {"store_id": "FL-445", "store_name": "Walmart Supercenter St. Petersburg", "city": "St. Petersburg", "state": "Fla.", "zip_code": "33701", "latitude": 27.7676, "longitude": -82.6403, "region": "West"},
    {"store_id": "FL-302", "store_name": "Walmart Supercenter Lakeland", "city": "Lakeland", "state": "Florida", "zip_code": "33801", "latitude": 28.0395, "longitude": -81.9498, "region": "Central"},
    {"store_id": "FL-710", "store_name": "Walmart Supercenter Pensacola", "city": "Pensacola", "state": "FL", "zip_code": "32501", "latitude": 30.4213, "longitude": -87.2169, "region": "Panhandle"},
    {"store_id": "FL239", "store_name": "Walmart Supercenter Orlando", "city": "Orlando", "state": "FL", "zip_code": "32801", "latitude": 28.5383, "longitude": -81.3792, "region": "Central"},
    {"store_id": "FL_287", "store_name": "Walmart Neighborhood Market Kissimmee", "city": "Kissimmee", "state": "Florida", "zip_code": "34741", "latitude": 28.292, "longitude": -81.4076, "region": "Central"},
])

print("Original row count:", len(stores_raw))
display(stores_raw)

Original row count: 14

,store_id,store_name,city,state,zip_code,latitude,longitude,region
0,FL-239,Walmart Supercenter Orlando,Orlando,FL,32801,28.5383,-81.3792,Central
1,FL-105,Walmart Supercenter Tampa,Tampa,FL,33602,27.9506,-82.4572,West
2,FL-330,Walmart Supercenter Miami,Miami,FL,33101,25.7617,-80.1918,South
3,FL-412,Walmart Supercenter Jacksonville,Jacksonville,FL,32099,30.3322,-81.6557,North
4,FL-287,Walmart Neighborhood Market Kissimmee,Kissimmee,Florida,34741,28.2920,-81.4076,Central
5,FL-156,Walmart Supercenter Daytona Beach,Daytona Beach,FL,32114,29.2108,-81.0228,East
6,FL-501,Walmart Supercenter Fort Myers,Fort Myers,FL,33901,26.6406,-81.8723,West
7,FL-078,Walmart Supercenter Gainesville,Gainesville,FL,32601,29.6516,-82.3248,North
8,FL-619,Walmart Supercenter Tallahassee,Tallahassee,FL,32301,NaN,NaN,Panhandle
9,FL-445,Walmart Supercenter St. Petersburg,St. Petersburg,Fla.,33701,27.7676,-82.6403,West
10,FL-302,Walmart Supercenter Lakeland,Lakeland,Florida,33801,28.0395,-81.9498,Central
11,FL-710,Walmart Supercenter Pensacola,Pensacola,FL,32501,30.4213,-87.2169,Panhandle
12,FL239,Walmart Supercenter Orlando,Orlando,FL,32801,28.5383,-81.3792,Central
13,FL_287,Walmart Neighborhood Market Kissimmee,Kissimmee,Florida,34741,28.2920,-81.4076,Central

transformed the data into a permanenet spot in this notebook because it is a smaller set.

In [6]:
import pandas as pd
import re

stores_raw

rows_before = len(stores_raw)


def clean_store_locations(df):
    clean = df.copy()

    text_columns = [
        "store_id", "store_name", "city",
        "state", "region"
    ]

    for col in text_columns:
        clean[col] = clean[col].astype("string").str.strip()

    clean["store_id"] = clean["store_id"].str.upper()
    clean["store_id"] = clean["store_id"].str.replace(
        r"^([A-Z]{2})[-_]?(\d+)$",
        r"\1-\2",
        regex=True
    )

    state_mapping = {
        "FLORIDA": "FL",
        "FLA.": "FL",
        "FL": "FL"
    }

    clean["state"] = (
        clean["state"]
        .str.upper()
        .replace(state_mapping)
    )

    clean["city"] = clean["city"].str.title()
    clean["store_name"] = clean["store_name"].str.title()

    clean["region"] = clean["region"].str.strip()

    clean = clean.drop_duplicates()

    clean = clean.drop_duplicates(
        subset=["store_id"],
        keep="first"
    )

    return clean


stores_clean = clean_store_locations(stores_raw)

rows_after = len(stores_clean)

print("Rows before cleaning:", rows_before)
print("Rows after cleaning:", rows_after)
print("Rows removed:", rows_before - rows_after)

display(stores_clean)

print("\nMissing values:")
print(stores_clean.isna().sum())

print("\nDuplicate store IDs:", stores_clean["store_id"].duplicated().sum())

print("\nData types:")
print(stores_clean.dtypes)

Rows before cleaning: 14
Rows after cleaning: 12
Rows removed: 2

,store_id,store_name,city,state,zip_code,latitude,longitude,region
0,FL-239,Walmart Supercenter Orlando,Orlando,FL,32801,28.5383,-81.3792,Central
1,FL-105,Walmart Supercenter Tampa,Tampa,FL,33602,27.9506,-82.4572,West
2,FL-330,Walmart Supercenter Miami,Miami,FL,33101,25.7617,-80.1918,South
3,FL-412,Walmart Supercenter Jacksonville,Jacksonville,FL,32099,30.3322,-81.6557,North
4,FL-287,Walmart Neighborhood Market Kissimmee,Kissimmee,FL,34741,28.2920,-81.4076,Central
5,FL-156,Walmart Supercenter Daytona Beach,Daytona Beach,FL,32114,29.2108,-81.0228,East
6,FL-501,Walmart Supercenter Fort Myers,Fort Myers,FL,33901,26.6406,-81.8723,West
7,FL-078,Walmart Supercenter Gainesville,Gainesville,FL,32601,29.6516,-82.3248,North
8,FL-619,Walmart Supercenter Tallahassee,Tallahassee,FL,32301,NaN,NaN,Panhandle
9,FL-445,Walmart Supercenter St. Petersburg,St. Petersburg,FL,33701,27.7676,-82.6403,West
10,FL-302,Walmart Supercenter Lakeland,Lakeland,FL,33801,28.0395,-81.9498,Central
11,FL-710,Walmart Supercenter Pensacola,Pensacola,FL,32501,30.4213,-87.2169,Panhandle

Missing values:
store_id      0
store_name    0
city          0
state         0
zip_code      0
latitude      1
longitude     1
region        0
dtype: int64

Duplicate store IDs: 0

Data types:
store_id      string[python]
store_name    string[python]
city          string[python]
state         string[python]
zip_code              object
latitude             float64
longitude            float64
region        string[python]
dtype: object

Decision Log:

Made the columns:  "store_id", "store_name", "city",
        "state", "region"

Cleaned the store IDs to all be FL-###

Made all of the state abbreviations FL

Made all of the cities and store names Title Capitization

Strip the one space around Panhandle in the regions

Drop the FL-239 duplicate